// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"mt-auto border-t border-brown-200 bg-brown-50\"><div class=\"container mx-auto px-4 py-8\"><div class=\"flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0\"><div class=\"text-sm text-brown-700\"><span class=\"font-semibold text-brown-900\">Arabica</span> - Your brew, your data</div><nav class=\"flex flex-wrap justify-center gap-6 text-sm\"><a href=\"/about\" class=\"text-brown-700 hover:text-brown-900 transition-colors\">About</a> <a href=\"/terms\" class=\"text-brown-700 hover:text-brown-900 transition-colors\">Terms of Service</a> <a href=\"https://github.com/ptdewey/arabica\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-brown-700 hover:text-brown-900 transition-colors\">Source Code</a> <a href=\"https://atproto.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-brown-700 hover:text-brown-900 transition-colors\">AT Protocol</a></nav></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
