// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "arabica/internal/bff"

// LayoutData contains all the data needed for the layout
type LayoutData struct {
	Title           string
	IsAuthenticated bool
	UserDID         string
	UserProfile     *bff.UserProfile
}

func Layout(data *LayoutData, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"h-full\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Arabica is a coffee brew tracking app built on AT Protocol. Your brewing data is stored in your own Personal Data Server, giving you full ownership and portability.\"><meta property=\"og:title\" content=\"Arabica - Coffee Brew Tracker\"><meta property=\"og:description\" content=\"Track your coffee brewing journey. Built on AT Protocol, your data stays yours.\"><meta property=\"og:type\" content=\"website\"><meta name=\"theme-color\" content=\"#4a2c2a\"><meta name=\"view-transition\" content=\"same-origin\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/layout.templ`, Line: 25, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - Arabica</title><link rel=\"icon\" href=\"/static/favicon.svg\" type=\"image/svg+xml\"><link rel=\"icon\" href=\"/static/favicon-32.svg\" type=\"image/svg+xml\" sizes=\"32x32\"><link rel=\"apple-touch-icon\" href=\"/static/icon-192.svg\"><link rel=\"stylesheet\" href=\"/static/css/output.css?v=0.3.0\"><link rel=\"stylesheet\" href=\"/static/css/transitions.css?v=0.3.0\"><style>\n\t\t\t[x-cloak] { display: none !important; }\n\t\t\t/* Ensure smooth transitions during HTMX swaps */\n\t\t\t.htmx-swapping { opacity: 0; transition: opacity 200ms ease-out; }\n\t\t\t.htmx-settling { opacity: 1; transition: opacity 200ms ease-in; }\n\t\t</style><link rel=\"manifest\" href=\"/static/manifest.json\"><script>\n\t\t\t// Configure HTMX before it loads\n\t\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\t\tif (typeof htmx !== 'undefined') {\n\t\t\t\t\t// Disable view transitions - using component-level animations instead\n\t\t\t\t\t// View transitions were causing double-fade issues\n\t\t\t\t\thtmx.config.globalViewTransitions = false;\n\t\t\t\t}\n\t\t\t});\n\t\t</script><!-- Load entity manager and dropdown manager modules before Alpine components --><script src=\"/static/js/entity-manager.js?v=0.1.0\"></script><script src=\"/static/js/dropdown-manager.js?v=0.1.0\"></script><!-- Load Alpine components BEFORE Alpine.js initializes --><script src=\"/static/js/brew-form.js?v=0.3.2\"></script><!-- Load Alpine.js core with defer (will initialize after DOM loads) --><script src=\"/static/js/alpine.min.js?v=0.2.0\" defer></script><!-- Load HTMX and other utilities --><script src=\"/static/js/htmx.min.js?v=0.2.0\"></script><script src=\"/static/js/transitions.js?v=0.2.0\"></script><script src=\"/static/js/entity-helpers.js?v=0.5.0\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.IsAuthenticated {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<script src=\"/static/js/data-cache.js?v=0.2.0\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<script src=\"/static/js/back-button.js?v=0.3.1\"></script><script src=\"/static/js/sw-register.js?v=0.2.0\"></script></head><body class=\"bg-brown-50 min-h-full flex flex-col\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.UserDID != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " data-user-did=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.UserDID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/layout.templ`, Line: 68, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Header(data.IsAuthenticated, data.UserProfile).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<main class=\"flex-grow container mx-auto px-4 py-8\" data-transition>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<!-- Modal container for entity dialogs --><div id=\"modal-container\"></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
